### ISSUE TITLE
BUG: dde-calendar 在 debian 下无法运行

### ISSUE THREAD

**Issue by quanzhuo** [linuxdeepin/dde-calendar#10]
您好: deepin calendar 在 debian 上无法启动,详细信息如下, 期望得到您的回复, 感谢!

## 前提条件
+ OS: debian testing
+ dde-calendar: 1.2.5-1
+ sudo apt install dde-calendar\

## 实际结果
+ 在 launcher 中点击 deepin calendar 图标无法启动 calendar
+ 在 终端中执行 dde-calendar, 出现如下错误:

    > dde-calendar: symbol lookup error: dde-calendar: undefined symbol: _ZN3Dtk6Widget12DApplication14setProductIconERK7QPixmap

## 期望结果
可以正常运行 deepin calendar

**Comment by hualet** [comment]
额 这个是不是要麻烦 @hosiet 看看？版本没有更新？

**Comment by hosiet** [comment]
感谢指出问题，我已经在 debian unstable 做了一个修复（其实只是重新构建了一下），等 unstable 的包迁移到 testing 后即可解决问题。另外建议在 Debian 中的包今后使用 Debian 官方的问题报告途径来报告，要不然维护者可能看不见。

@hualet 这个 issue 应该可以关掉了，谢谢

**Comment by qrqhuang** [comment]
我想知道 ubuntu 版 没有农历吗...

**Comment by hosiet** [comment]
@qrqhuang dde-calendar 的农历功能需要 dde-api 才能启用；鉴于 Debian 内处理 deepin 包的志愿者没有人足够熟悉 dde-api 的编程语言 golang，这个包没人打包。有能力的话欢迎前来贡献。
