### ISSUE TITLE
Shortcut support

### ISSUE THREAD

**Issue by amit-gshe** [linuxdeepin/dde-calendar#12]
Is there plans to add some shortcut supports such as: Esc to exit the window?

**Comment by BLumia** [comment]
I don't think that should be done on the application side, probably it's better to config custom shortcut for your window manager?

**Comment by amit-gshe** [comment]
Window manager, I agree it can manage the window behaviors but it can not replace the shortcut. The shortcut can improve the user experience and make the app more effeciency and elegant.

**Comment by z966768** [comment]
Thank you for your great idea, we will consider
