### ISSUE TITLE
The year selector stops at 1900 but one can still access earlier dates via the month selector

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/dde-calendar#2]
The left(<) button of year selector greys out at 1900 but one can still access 1899, 1898 etc by clicking the left(<) button of the month selector.

Here a screenshot that I kept clicking the month selector until the year field reaches zero. The whole calendar are filled with zero in such case, and debug logs says `set current date  QDate("")`.

![2016-09-22-222314-f9dfd1](https://cloud.githubusercontent.com/assets/1006477/18751937/69b829ce-8113-11e6-9016-5f77523b9e8e.png)

**Comment by z966768** [comment]
Please use the new version
