### ISSUE TITLE
Feature Request: simple events or integration

### ISSUE THREAD

**Issue by ElianVanCutsem** [linuxdeepin/dde-calendar#24]
it's 2020 and still no use for the calendar. Is it possible to make this?

**Comment by BLumia** [comment]
It's planned and will be there in the upcoming v20 release, but sadly there is still no ETA for v20 release...

**Comment by ElianVanCutsem** [comment]
That's great! I'm happy to hear that.   I'm using deepin as a daily driver since a week. I've experienced very awesome features, but also noticed a great deal of bugs. I'll report them as they come. I'll also try to improve features via GitHub.

Fyi, i also opened a pull request on dde-dock for the trash plugin
