### ISSUE TITLE
Add screenshot

### ISSUE THREAD

**Issue by acestronautical** [linuxdeepin/dde-calendar#25]
No screenshot appears in this repo, and no screenshot appears on https://packages.ubuntu.com/focal/dde-calendar.

There is a screenshot at https://www.deepin.org/en/original/dde-calendar/

**Comment by BLumia** [comment]
https://screenshots.debian.net/package/dde-calendar

**Comment by YutianGe** [comment]
Take screenshots using deepin-screen-recorder
