### ISSUE TITLE
Space between week table headers are smaller than the table contents

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/dde-calendar#3]
第一个 "31" 的中心相比 "周日" 偏左，而第一个 "6" 的中心则在 "周六" 中心的右边。

![2016-09-22-223016-191fb0](https://cloud.githubusercontent.com/assets/1006477/18752290/89abe814-8114-11e6-8226-4d696656afe7.png)

**Comment by manateelazycat** [comment]
@hualet 这个是　bug  修吧。　;)

**Comment by z966768** [comment]
Please use the new version
