### ISSUE TITLE
Add setting to change first day on week

### ISSUE THREAD

**Issue by Duke1715** [linuxdeepin/dde-calendar#32]
In this moment in Deepin 20 beta last relase steel we can`t choose setting about first day in week. For now it`s Sunday, but in most countrys it`s Monday.

**Comment by Saduff** [comment]
Yes please, same issue here: https://github.com/linuxdeepin/developer-center/issues/259#issuecomment-664949246

**Comment by z966768** [comment]
Thanks for your feedback, we have collected

**Comment by YutianGe** [comment]
https://github.com/linuxdeepin/dde-calendar/issues/41  same issue
