### ISSUE TITLE
可以提供选项来添加更多中国农历信息的支持吗?

### ISSUE THREAD

**Issue by xtdumpling** [linuxdeepin/dde-calendar#33]
1. 可以提供选项来添加中国农历二十四节气信息吗?
例如,立春,秋分,冬至,大暑等等.

2. 新建日程的时候,添加农历日期和重复设定
例如,支持每年的腊月初八提示吃腊八粥.

谢谢!

**Comment by z966768** [comment]
我们已收集您的建议，谢谢反馈

**Comment by xtdumpling** [comment]
深度系统更新（2020.11.13）版本的日历中已经支持显示中国农历二十四节气了!
谢谢!
