### ISSUE TITLE
是否能webcal和ics文件支持？

### ISSUE THREAD

**Issue by sagezhj** [linuxdeepin/dde-calendar#35]
是否能考虑增加webcal和苹果的ics格式支持？下载gnome日历可以支持上述格式，但是一是原生没有中国节假日和节气之类的本地化内容，二是界面是在不搭

**Comment by z966768** [comment]
我们已收集您的建议，谢谢反馈 。

**Comment by z966768** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
