### ISSUE TITLE
Add more lunar calendar

### ISSUE THREAD

**Issue by Chavahtem** [linuxdeepin/dde-calendar#38]
Hello developers,

my friend from Vietnam told me that he didn't find an option in Deepin Calendar to display the Vietnamese lunar calendar.

Can you add it in Deepin?

I can confirm it (missing) and I use Deepin 20.

**Comment by z966768** [comment]
Thank you for your opinion, we may consider it later

**Comment by Chavahtem** [comment]
@z966768 
Thanks for the answer. I tested again under new Deepin 20.1 version and it is missing.

My friend says he doesn't know of any Linux distributions where the default calendar has the Vietnamese lunar calendar added. Please add.

Do you know how to calculate the vietnamese lunar calendar?
If not I found this website. It shows how to calculate it and has a live calendar (vietnamese lunar calendar) integrated on top.
https://www.informatik.uni-leipzig.de/~duc/amlich/calrules_en.html
