### ISSUE TITLE
European calendar formats missing

### ISSUE THREAD

**Issue by scroom** [linuxdeepin/dde-calendar#40]
As described above. Currently, only date formats that start with the year are possible. However, in many European countries it is common to start with the day. So not 2020/01/04, but e.g. 04/01/2020 (with dots) or 04/01/2020.

Also the written out long date begins e.g. in German with the day, thus e.g. 04 January 2020.

It would be great if these functions could be added. Maybe you can get impressions from other distributions here?

**Comment by z966768** [comment]
Thank you for your feedback, it has been reported up

**Comment by YutianGe** [comment]
repeat issue:https://github.com/linuxdeepin/dde-calendar/issues/42
