### ISSUE TITLE
Calendar view does not adjust to the first day of the week

### ISSUE THREAD

**Issue by scroom** [linuxdeepin/dde-calendar#41]
As described above. In the settings, the first day of the week is correctly set to Monday, which is common in Europe. But unfortunately the calendar does not adapt, it continues to show Sunday on the far left, i.e. as the first day of the week.
![Bildschirmfoto vom 2021-01-04 21-31-55](https://user-images.githubusercontent.com/5347731/103577034-59b50180-4ed4-11eb-9605-26217b23c14a.png)

**Comment by z966768** [comment]
Thank you for your feedback, it has been reported up

**Comment by YutianGe** [comment]
It is supported. Set the calendar format in the "Control Center". Thank you for your feedback
