### ISSUE TITLE
Date format and width "ALL DAY" for European countries

### ISSUE THREAD

**Issue by roxfr** [linuxdeepin/dde-calendar#42]
Hi,
Could you change for European countries :
- the YYYY/MM/DD format in DD/MM/YYYY,
- the size for the translation of "ALL DAY".
Thank you.
Regards,
Roxfr

![image](https://user-images.githubusercontent.com/52124613/110977604-a8629a00-8362-11eb-8fd3-bbe7e11ceb81.png)

**Comment by z966768** [comment]
Thank you for your support,We will contact the product manager to improve

**Comment by roxfr** [comment]
@YutianGe
Hi,
Following the close of bug #40 #42 reports, do you have correct the problem?
Thank you.
Regards,
Roxfr
