### ISSUE TITLE
[dde-calendar] Change the first day

### ISSUE THREAD

**Issue by Urgau** [linuxdeepin/dde-calendar#44]
Hello,

In dde-calendar, the first day is Sunday however in Europe, in North America and other countries the first day off the week is the **Monday** not Sunday. Can you please change this quickly. Thanks you.

**Comment by chenhaifeng-ut** [comment]
> Hello,
> 
> In dde-calendar, the first day is Sunday however in Europe, in North America and other countries the first day off the week is the **Monday** not Sunday. Can you please change this quickly. Thanks you.

Hi，In the latest version, the first day of the week can be modified through the control center.

**Comment by Sky-Asher** [comment]
No feedback has been received on this issue for more than 1 month. The issue will be closed soon. Thank you for your support
