### ISSUE TITLE
Deepin Calendar not at all useful 

### ISSUE THREAD

**Issue by cacarr-pdxweb** [linuxdeepin/dde-calendar#45]
The lack of ability to sync with cloud calendar services like Google Calendar, Apple Calendar, etc, makes this software completely useless. Continued development of it serves no purpose.

**Comment by chenhaifeng-ut** [comment]
> The lack of ability to sync with cloud calendar services like Google Calendar, Apple Calendar, etc, makes this software completely useless. Continued development of it serves no purpose.

Thank you for your proposal. We will give feedback to the product.

**Comment by Sky-Asher** [comment]
No feedback has been received on this issue for more than 1 month. The issue will be closed soon. Thank you for your support
