### ISSUE TITLE
Nepali Calendar follows the Bikram sambat system.

### ISSUE THREAD

**Issue by sarojpoudel33** [linuxdeepin/dde-calendar#46]
Nepali Calendar follows the Bikram sambat system which uses lunar months and solar sidereal year
Nepali calendar is approximately 56 years and 8½ months ahead of the Gregorian calendar (A.D). So we have difficult to Know AD. I can provide all data of Bikram Sambat (BS).

**Comment by chenhaifeng-ut** [comment]
> Nepali Calendar follows the Bikram sambat system which uses lunar months and solar sidereal year
> Nepali calendar is approximately 56 years and 8½ months ahead of the Gregorian calendar (A.D). So we have difficult to Know AD. I can provide all data of Bikram Sambat (BS).

Thank you for your proposal. We will give feedback to the product

**Comment by Sky-Asher** [comment]
No feedback has been received on this issue for more than 1 month. The issue will be closed soon. Thank you for your support
