### ISSUE TITLE
add alternative calendar support

### ISSUE THREAD

**Issue by chenzhiwei** [linuxdeepin/dde-calendar#47]
In Chinese mode, there is an extra Chinese Calendar, but please support setting Chinese Calendar in other languages.

![image](https://user-images.githubusercontent.com/672668/137447045-da1fb962-bfb5-417a-9761-ff767d627103.png)

**Comment by Sky-Asher** [comment]
Thank you for your support. I will feed back this question to the product manager.

**Comment by Sky-Asher** [comment]
The product personnel have accepted this demand.

**Comment by Liubin-scorpio** [comment]
This problem has been fed back to the product. It has been more than 1 month, the other party has no feedback, and the problem will be closed soon
