### ISSUE TITLE
duplicate menu entries

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/dde-calendar#5]
![calendar_menu](https://user-images.githubusercontent.com/11800714/27520831-3b083332-5a14-11e7-99f4-84ec3fdd18c3.png) :)

**Comment by mrmango** [comment]
Just to add, each About entry seems to show different content:

Top option:

![image](https://user-images.githubusercontent.com/612731/27595155-cc0f614e-5b53-11e7-842e-f365699bf65b.png)

Third option:

![image](https://user-images.githubusercontent.com/612731/27595256-14023594-5b54-11e7-9e20-f52339ba8ca5.png)

Thanks

**Comment by BLumia** [comment]
Seems already fixed, closing.

Let us know if you still have this issue.
