### ISSUE TITLE
dtkwidget

### ISSUE THREAD

**Issue by baimafeima** [linuxdeepin/dde-calendar#6]
@felixonmars @kirigayakazushin Not sure who is maintaining dde-calendar, hopefully pinging the right one. Is it possible to build dde-calendar without `dtkwidget` or in any sense to make dde-calendar more distribution-agnostic?

**Comment by felixonmars** [comment]
No. You should package `dtkwidget` for your distro before packaging dde-calendar.

**Comment by baimafeima** [comment]
Thanks for the quick feedback. I had originally suggested `dde-calendar` to be added to the repositories of my favourite Linux-based distribution but as `dtkwidget` cannot be added at this time, I am wondering whether you would consider offering a `snap package `for easy cross-platform installation.

**Comment by felixonmars** [comment]
I don't think they are working on snap. You may expect a `flatpak`, though.

**Comment by baimafeima** [comment]
A `flatpak` sounds good too.
