### ISSUE TITLE
Why is it useless ?

### ISSUE THREAD

**Issue by ademcal** [linuxdeepin/dde-calendar#8]
Because of that reasons

can't sync with  Gmail, Yahoo ...
can't show haliday days
can't add notes
can't add alarm 

Why am I use ...

**Comment by sudipmandal** [comment]
Here is a project which syncs google calendar with deepin calendar

[https://github.com/sudipmandal/deepin-ext-cal-sync](https://github.com/sudipmandal/deepin-ext-cal-sync)

**Comment by z966768** [comment]
Thank you for your great idea, we will consider
